<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["assets", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit assets
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "assets/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldValue" class="col-sm-2 control-label">Value</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["value", "type" => "number", "class" => "form-control", "id" => "fieldValue"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCoin" class="col-sm-2 control-label">Coin</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["coin", "type" => "number", "class" => "form-control", "id" => "fieldCoin"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldWallet" class="col-sm-2 control-label">Wallet</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["wallet", "type" => "number", "class" => "form-control", "id" => "fieldWallet"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
