<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search assets
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["assets/new", "Create assets"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "assets/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldValue" class="col-sm-2 control-label">Value</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["value", "type" => "number", "class" => "form-control", "id" => "fieldValue"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCoin" class="col-sm-2 control-label">Coin</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["coin", "type" => "number", "class" => "form-control", "id" => "fieldCoin"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldWallet" class="col-sm-2 control-label">Wallet</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["wallet", "type" => "number", "class" => "form-control", "id" => "fieldWallet"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
